version: 3
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:z
  
  redis:
    image: redis:6.0.10-alpine

  enigma:
    image: dessolo/enigma:1.1.0
    volumes:
      - ./enigma/config.yml:/etc/enigma/config.yml:z
