version: "3"

services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:z
  
  redis:
    image: redis:7.4.5-alpine3.21
    ports:
      - "6379:6379"

  enigma:
    image: dessolo/enigma2:latest
    volumes:
      - ./enigma/config.yml:/etc/enigma/config.yml:z
